<?php

namespace Database\Seeders;

use App\Models\TindakanPatient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TindakanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "name" => "Thorax",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "72476",
                "icd" => "87.49",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "fisioteraphy",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "100000",
                "tarif_uc" => "70000",
                "icd" => "93.39",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Buka gips",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "160000",
                "tarif_uc" => "135000",
                "icd" => "97.88",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Photo Abdomen 2 Posisi",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "138748",
                "icd" => "87.65",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Kultur Darah",
                "category" => "Laboratorium",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "255000",
                "tarif_uc" => "225000",
                "icd" => "90.53",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Pelvis",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "72476",
                "icd" => "88.26",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Cranium",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "123577",
                "icd" => "87.17",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Lumbo Sacral",
                "category" => "Rontgen",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "156000",
                "tarif_uc" => "102748",
                "icd" => "87.24",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Femur",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78472",
                "icd" => "88.27",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Cruris",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78472",
                "icd" => "88.27",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Genu",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78472",
                "icd" => "88.27",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Ankle / Talocruralis",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.28",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Cubiti / Siku",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "4",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.22",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Wrist Joint / Pergelangan tangan",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.23",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Manus / Tangan",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.23",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Humerus",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.21",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Antebrachii",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.22",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Pedis",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.28",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Calcaneus",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.28",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Gleno Humeral / Sendi Bahu / Shoulder",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.21",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Photo BNO",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "72476",
                "icd" => "87.79",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Clavicula",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "101638",
                "icd" => "87.43",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Vertebrae Lumbosacral",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "126577",
                "icd" => "87.24",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Appendicogram",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "465000",
                "tarif_uc" => "219890",
                "icd" => "87.69",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "IVP",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "660000",
                "tarif_uc" => "650000",
                "icd" => "87.73",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Tukar Verban Kecil",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "30000",
                "tarif_uc" => "14685",
                "icd" => "93.57",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Tukar Verban Sedang",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "40000",
                "tarif_uc" => "23449",
                "icd" => "93.57",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Tukar Verban Besar",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "55000",
                "tarif_uc" => "35905",
                "icd" => "93.57",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Incisi Abses Kecil",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "500000",
                "tarif_uc" => "",
                "icd" => "86.09",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Incisi Abses Sedang",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "500000",
                "tarif_uc" => "",
                "icd" => "86.09",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Incisi Abses Besar",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "500000",
                "tarif_uc" => "",
                "icd" => "86.09",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Heating < 5 ",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "60000",
                "tarif_uc" => "29750",
                "icd" => "93.57",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Heating 5-10",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "100000",
                "tarif_uc" => "650000",
                "icd" => "93.57",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Heating > 10",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "150000",
                "tarif_uc" => "63750",
                "icd" => "93.57",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Skin Traksi",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "85000",
                "tarif_uc" => "60000",
                "icd" => "93.46",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Pasang Spalak Kecil",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "110000",
                "tarif_uc" => "90000",
                "icd" => "93.54",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Pasang Spalak Sedang",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "135000",
                "tarif_uc" => "105000",
                "icd" => "93.54",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Pasang Spalak Besar",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "160000",
                "tarif_uc" => "130000",
                "icd" => "93.54",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Pasang NGT",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "50000",
                "tarif_uc" => "21250",
                "icd" => "96.07",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Aff Catheter",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "25000",
                "tarif_uc" => "8350",
                "icd" => "57.95",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Photo Uretro-Cystografi",
                "category" => "Rontgen",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "500000",
                "tarif_uc" => "",
                "icd" => "87.77",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Photo Cystografi",
                "category" => "Rontgen",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "425000",
                "tarif_uc" => "",
                "icd" => "87.77",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Sinus Paranasal",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "123577",
                "icd" => "87.16",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Echocardiografi",
                "category" => "Echocardiografi",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "500000",
                "tarif_uc" => "375000",
                "icd" => "88.72",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Nebulisasi ",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "55000",
                "tarif_uc" => "27000",
                "icd" => "93.94",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Aff Heating Dinding Abdomen",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "40000",
                "tarif_uc" => "11490",
                "icd" => "97.83",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Servical",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "123577",
                "icd" => "87.22",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "USG UROLOGI (PRINT)",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "195000",
                "tarif_uc" => "64500",
                "icd" => "88.75",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "USG ABDOMEN (PRINT)",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "350000",
                "tarif_uc" => "64500",
                "icd" => "88.76",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Aspirasi",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "110000",
                "tarif_uc" => "19840",
                "icd" => "85.91",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Aspirasi Abses / Bulae",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "50000",
                "tarif_uc" => "",
                "icd" => "86.01",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Uroflowmetri",
                "category" => "UROFLOWMETRI",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "110000",
                "tarif_uc" => "22500",
                "icd" => "89.24",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "USG UROLOGI (NON PRINT)",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "105000",
                "tarif_uc" => "55500",
                "icd" => "88.75",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "USG ABDOMEN (NON PRINT)",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "105000",
                "tarif_uc" => "55500",
                "icd" => "88.76",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN THORAX ",
                "category" => "Rontgen",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "800000",
                "tarif_uc" => "750000",
                "icd" => "87.41 (TOP UP)",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN KEPALA / BRAIN",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "1030000",
                "tarif_uc" => "980000",
                "icd" => "87.03 (TOP UP)",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN ABDOMEN/UROLOGI",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "1030000",
                "tarif_uc" => "980000",
                "icd" => "88.01 (TOP UP)",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "MRI THORAX",
                "category" => "MRI",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "88.92 (TOP UP)",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "MRI TULANG BELAKANG",
                "category" => "MRI",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "88.93 (TOP UP)",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "MRI LOKASI LAIN/ TIDAK SPESIFIK",
                "category" => "MRI",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "88.97",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "USG THYROID",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "350000",
                "tarif_uc" => "285970",
                "icd" => "88.71",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "BARIUM ENEMA",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "610000",
                "tarif_uc" => "600000",
                "icd" => "87.64",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "USG MAMMAE",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "350000",
                "tarif_uc" => "285970",
                "icd" => "88.73",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "USG TESTIS",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "350000",
                "tarif_uc" => "282970",
                "icd" => "88.79",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Aff Heating Punggung",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "55000",
                "tarif_uc" => "11490",
                "icd" => "97.84",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN Lain-lain",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "1030000",
                "tarif_uc" => "980000",
                "icd" => "88.38",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "BAJAH PAYUDARA",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "85.11",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "AUDIOMETRI",
                "category" => "AUDIOMETRI",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "90000",
                "tarif_uc" => "80000",
                "icd" => "95.41",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "BUKA GIBS",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "97.88",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Fistulografi Esofagus/ tempat lain",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "88.49",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Fistulografi Dinding Abdomen",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "88.03",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Fistulografi dinding dada",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "87.38",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Fistulografi Retroperitoneum",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "88.14",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "MAMMOGRAFI",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "5000",
                "tarif_uc" => "",
                "icd" => "87.37",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Rontgen Panoramik",
                "category" => "Rontgen",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "87.12",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Irigasi telinga / Ektraksi Serumen",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "45000",
                "tarif_uc" => "7470",
                "icd" => "96.52",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CAUSTIK/ EKSISI LESI TELINGA TENGAH",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "20.79",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "REMOVAL NASSAL PACKING/BUKA TAMPON HIDUNG",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "97.32",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "LARINGOSKOPI",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "165000",
                "tarif_uc" => "85000",
                "icd" => "31.42",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "EKSTRAKSI BENDA ASING THT",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "182000",
                "tarif_uc" => "102000",
                "icd" => "98.11",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "IRIGASI HIDUNG",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "300000",
                "tarif_uc" => "225000",
                "icd" => "96.53",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CAUSTIK/ EKSISI LESI TELINGA LUAR",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "18.29",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CAUSTIC/EKSISI LESI HIDUNG",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "",
                "tarif_uc" => "",
                "icd" => "21.30",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN NASOFARING ",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "1128000",
                "tarif_uc" => "1078000",
                "icd" => "88.38 (TOP UP)",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "BAJAH PAYUDARA",
                "category" => "BAJAH",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "112000",
                "tarif_uc" => "102000",
                "icd" => "85.11",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "BAJAH KELENJAR TIROID",
                "category" => "BAJAH",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "112000",
                "tarif_uc" => "102000",
                "icd" => "06.11",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "BAJAH KELENJAR LYMFE",
                "category" => "BAJAH",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "112000",
                "tarif_uc" => "102000",
                "icd" => "40.11",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Nasal / Hidung",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "123577",
                "icd" => "87.16",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Elbow Joint",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "127000",
                "tarif_uc" => "78775",
                "icd" => "88.22",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "Vertebrae Thorakolumbal",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "166000",
                "tarif_uc" => "102748",
                "icd" => "87.23",
                "st_tindak" => "0",
                "ak_tindak" => "1",
                "lpa" => "0",
            ],
            [
                "name" => "CABUT K WIRE",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "110000",
                "tarif_uc" => "5000",
                "icd" => "97.88",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Rontgen Panoramic",
                "category" => "Rontgen",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "185500",
                "tarif_uc" => "135500",
                "icd" => "87.12",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Analisa Gas Darah",
                "category" => "Laboratorium",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "182000",
                "tarif_uc" => "155000",
                "icd" => "89.65",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Malaria Parasitologi",
                "category" => "Laboratorium",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "68500",
                "tarif_uc" => "31000",
                "icd" => "90.54",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Malaria",
                "category" => "Laboratorium",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "110000",
                "tarif_uc" => "62000",
                "icd" => "90.54",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Kultur Pus",
                "category" => "Laboratorium",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "255000",
                "tarif_uc" => "225000",
                "icd" => "91.73",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN THORAX",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "883000",
                "tarif_uc" => "833000",
                "icd" => "87.41",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN LEHER",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "1128000",
                "tarif_uc" => "1078000",
                "icd" => "88.38",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "USG LEHER",
                "category" => "USG",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "350000",
                "tarif_uc" => "285970",
                "icd" => "88.71",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "IRRIGATION TELINGA",
                "category" => "JASA TINDAKAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "45000",
                "tarif_uc" => "30000",
                "icd" => "96.52",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN ANTEBRACHII",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "1030000",
                "tarif_uc" => "980000",
                "icd" => "88.38",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "CT SCAN CRURIS",
                "category" => "CT SCAN",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "1",
                "konsul_not" => "N",
                "tarif_umum" => "1030000",
                "tarif_uc" => "980000",
                "icd" => "88.38",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Infra Red Radiasi",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.35",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Latihan Pergerakan Sendi",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.14",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Latihan Bagian Tubuh yang Kaku",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.13",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Latihan Pernafasan",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.18",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Latihan Muskuloskeletal Aktif lainnya",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.12",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Latihan Muskuloskeletal Pasif Lainnya",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.17",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Excercise, Unsp",
                "category" => "fisioteraphy",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "130000",
                "tarif_uc" => "70000",
                "icd" => "93.19",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Endoskopi Sinonasal",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "N",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "185000",
                "tarif_uc" => "152470",
                "icd" => "22.19",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
            [
                "name" => "Endoskopi Telinga / Otoscopy",
                "category" => "Tindakan / Parasat",
                "aktif_tindakan" => "Y",
                "askes" => "Y",
                "batas" => "5",
                "konsul_not" => "N",
                "tarif_umum" => "300000",
                "tarif_uc" => "225000",
                "icd" => "18.19",
                "st_tindak" => "0",
                "ak_tindak" => "0",
                "lpa" => "0",
            ],
        ];
        foreach ($data as $item){
            TindakanPatient::create($item);
        }
    }
}
