<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->delete();
        // $password = Hash::make('Ropana2023');
        $password = Hash::make('1234');
        $data = [
            [
                'id' => 10,
                'name' => 'Administrator',
                'nik' => '13090416080001',
                'email' => 'admin',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'admin RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '123245',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 11,
                'name' => 'petugas radiologi',
                'nik' => '13090416080001',
                'email' => 'petugasradiologi',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'petugasradiologi RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '12324556',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 12,
                'name' => 'Kasir',
                'nik' => '13090416080001',
                'email' => 'kasir',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'kasir RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '123245',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 13,
                'name' => 'Rekam Medis',
                'nik' => '13090416080001',
                'email' => 'rekammedis',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'rekammedis RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '123245234',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 14,
                'name' => 'Petugas Gudang',
                'nik' => '13090416080001',
                'email' => 'gudangfarmasi',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'gudangfarmasi RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '12324123',
                'unit_id' => 1,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 15,
                'name' => 'Perawat',
                'nik' => '13090416080001',
                'email' => 'perawatrajal',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'perawat Rajal RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '12323415',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 16,
                'name' => 'dokter',
                'nik' => '13090416080001',
                'email' => 'dokterpoli',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'ucok RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => 'DR016',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a92570a3062.png',
                'isDokter' => true,
            ],
            [
                'id' => 17,
                'name' => 'Validator Radiologi',
                'nik' => '13090416080001',
                'email' => 'dokterradiologi',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'dokterradiologi RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => 'DR016',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
                'isDokter' => true,
            ],
            [
                'id' => 18,
                'name' => 'Petugas Laboratorium',
                'nik' => '13090416080001',
                'email' => 'petugaslaborpk',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'petugaslabor PK RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '123245878',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 19,
                'name' => 'Validator Laboratorium',
                'nik' => '13090416080001',
                'email' => 'dokterlaborpk',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'dokterlabor PK RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => 'DR015',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
                'isDokter' => true,
            ],
            [
                'id' => 20,
                'name' => 'Petugas Informasi',
                'nik' => '13090416080001',
                'email' => 'petugasinformasi',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'petugasinformasi RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '123245',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 25,
                'name' => 'Apoteker',
                'nik' => '13090416080001',
                'email' => 'apoteker',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'apoteker RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '23423434',
                'unit_id' => 2,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            [
                'id' => 29,
                'name' => 'casemix',
                'nik' => '13090416080001',
                'email' => 'casemix',
                'ayah' => 'ayah',
                'ibu' => 'ibu',
                'gender' => 'Pria',
                'status_kawin' => 'Single',
                'jumlah_anak' => 0,
                'tgl_lahir' => '2023-07-08',
                'tgl_masuk' => '2023-07-08',
                'telp' => '081378580551',
                'nama_kontak_darurat' => 'kodar',
                'no_kontak_darurat' => '081378580551',
                'alamat_ktp' => 'Padang',
                'alamat_domisili' => 'Padang',
                'alamat_kontak_darurat' => 'Padang',
                'pendidikan' => 'S3',
                'pengalaman' => 'Tidak Ada',
                'nama_rekening' => 'casemix RS',
                'no_rekening' => 1231232334,
                'catatan' => 'Tidak Ada',
                'staff_id' => '123248765',
                'unit_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => '',
            ],
            // [
            //     'id' => 31,
            //     'name' => 'Dokter Spesialis',
            //     'nik' => '13090416080001',
            //     'email' => 'dokterspesialis',
            //     'ayah' => 'ayah',
            //     'ibu' => 'ibu',
            //     'gender' => 'Pria',
            //     'status_kawin' => 'Single',
            //     'jumlah_anak' => 0,
            //     'tgl_lahir' => '2023-07-08',
            //     'tgl_masuk' => '2023-07-08',
            //     'telp' => '081378580551',
            //     'nama_kontak_darurat' => 'kodar',
            //     'no_kontak_darurat' => '081378580551',
            //     'alamat_ktp' => 'Padang',
            //     'alamat_domisili' => 'Padang',
            //     'alamat_kontak_darurat' => 'Padang',
            //     'pendidikan' => 'S3',
            //     'pengalaman' => 'Tidak Ada',
            //     'nama_rekening' => 'dokter jaga RS',
            //     'no_rekening' => 1231232334,
            //     'catatan' => 'Tidak Ada',
            //     'staff_id' => 'DR014',
            //     'unit_id' => null,
            //     'password' => $password,
            //     'status' => 'AKTIF',
            //     'paraf' => null,
            //     'isDokter' => true,
            // ],
            // [
            //     'id' => 32,
            //     'name' => 'Dokter Umum',
            //     'nik' => '13090416080001',
            //     'email' => 'dokterumum',
            //     'ayah' => 'ayah',
            //     'ibu' => 'ibu',
            //     'gender' => 'Pria',
            //     'status_kawin' => 'Single',
            //     'jumlah_anak' => 0,
            //     'tgl_lahir' => '2023-07-08',
            //     'tgl_masuk' => '2023-07-08',
            //     'telp' => '081378580551',
            //     'nama_kontak_darurat' => 'kodar',
            //     'no_kontak_darurat' => '081378580551',
            //     'alamat_ktp' => 'Padang',
            //     'alamat_domisili' => 'Padang',
            //     'alamat_kontak_darurat' => 'Padang',
            //     'pendidikan' => 'S3',
            //     'pengalaman' => 'Tidak Ada',
            //     'nama_rekening' => 'dokter jaga RS',
            //     'no_rekening' => 1231232334,
            //     'catatan' => 'Tidak Ada',
            //     'staff_id' => 'DR013',
            //     'unit_id' => null,
            //     'password' => $password,
            //     'status' => 'AKTIF',
            //     'paraf' => null,
            //     'isDokter' => true,
            // ],

            // new data from excel 19/05/2024
            [
                'id' => 34,
                'name' => 'dr.Sihol Paabanan, Sp.THT-KL',
                'nik' => 1309041608010001,
                'email' => 'sihol',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580551',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR001',
                'unit_id' => 2,
                'poliklinik_id' => 1,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a7be9bc33fb.png',
                'isDokter' => true,
                'sip' => '1122/891/DKK/IV/2022',
            ],
            [
                'id' => 35,
                'name' => 'dr.Yoel Reynaldo,Sp.JP',
                'nik' => 1309041608010002,
                'email' => 'yoel',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580552',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR002',
                'unit_id' => 2,
                'poliklinik_id' => 2,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a7cdf5c74d3.png',
                'isDokter' => true,
                'sip' => '1123/891/DKK/IV/2022',
            ],
            [
                'id' => 36,
                'name' => 'Dr. Dandianullah, Sp.Pd',
                'nik' => 1309041608010003,
                'email' => 'dandi',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580553',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR003',
                'unit_id' => 2,
                'poliklinik_id' => 3,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a587c776efd.png',
                'isDokter' => true,
                'sip' => '733.1971/SIPD/DPMPTSP-PDG/VI/2023',
            ],
            [
                'id' => 37,
                'name' => 'Dr. Airlangga Rambuci, Sp.Pd',
                'nik' => 1309041608010004,
                'email' => 'angga',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580554',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR004',
                'unit_id' => 2,
                'poliklinik_id' => 4,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a1530c366b2.png',
                'isDokter' => true,
                'sip' => '733.1972/SIPD/DPMPTSP-PDG/VI/2023',
            ],
            [
                'id' => 38,
                'name' => 'dr.Luthfi Zakiral,Sp.PD-KGEH',
                'nik' => 1309041608010005,
                'email' => 'luthfi',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580555',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR005',
                'unit_id' => 2,
                'poliklinik_id' => 5,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a92570a3062.png',
                'isDokter' => true,
                'sip' => '733.1173/SIPD/DPMPTSP-PDG/I/2023',
            ],
            [
                'id' => 39,
                'name' => 'dr,Roroy Ibara,SpB(K)Onk.M.Kes',
                'nik' => 1309041608010006,
                'email' => 'roroy',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580556',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR006',
                'unit_id' => 2,
                'poliklinik_id' => 6,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65a1512719add.png',
                'isDokter' => true,
                'sip' => '777/SDMK-JAMKES/DKK/III/2017',
            ],
            [
                'id' => 40,
                'name' => 'dr.Christine, Sp.PD',
                'nik' => 1309041608010007,
                'email' => 'deni',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Wanita',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580557',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR007',
                'unit_id' => 2,
                'poliklinik_id' => 7,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65ae15a4c646f.png',
                'isDokter' => true,
                'sip' => '2222/SDMK-JASMKES/DKK/XI/2019',
            ],
            [
                'id' => 41,
                'name' => 'dr. Syifa Azzahra, Sp.OT',
                'nik' => 1309041608010008,
                'email' => 'syifa',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Wanita',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580558',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR008',
                'unit_id' => 2,
                'poliklinik_id' => 8,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/65ae2517bf6d3.png',
                'isDokter' => true,
                'sip' => '733.1111/SIPD/DP,PTSP-PDG/III/2023',
            ],
            [
                'id' => 42,
                'name' => 'dr. Dewa Fadillah,SpB',
                'nik' => 1309041608010009,
                'email' => 'yahya',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Pria',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580559',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR009',
                'unit_id' => 6,
                'poliklinik_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/66a7a9f867fee.png',
                'isDokter' => true,
                'sip' => '3333/SDMK-JAMKES/DKK/IX/2019',
            ],
            [
                'id' => 43,
                'name' => 'Dr.dr.Ramona,SpB-SpU',
                'nik' => 1309041608010010,
                'email' => 'yevri',
                'ayah' => null,
                'ibu' => null,
                'gender' => 'Wanita',
                'status_kawin' => null,
                'jumlah_anak' => 0,
                'tgl_lahir' => null,
                'tgl_masuk' => null,
                'telp' => '081378580560',
                'nama_kontak_darurat' => null,
                'no_kontak_darurat' => null,
                'alamat_ktp' => null,
                'alamat_domisili' => null,
                'alamat_kontak_darurat' => null,
                'pendidikan' => null,
                'pengalaman' => null,
                'nama_rekening' => null,
                'no_rekening' => 0,
                'catatan' => null,
                'staff_id' => 'DR010',
                'unit_id' => 7,
                'poliklinik_id' => null,
                'password' => $password,
                'status' => 'AKTIF',
                'paraf' => 'assets/paraf-petugas/66a7a9f863575.png',
                'isDokter' => true,
                'sip' => '0909/Regdit-P.SDM/DKK/X/2015',
            ],



        ];

        // dd($data);
        foreach ($data as $item) {
            User::create($item);
        }
    }
}
