<?php

namespace App\Models\arg01;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Seps extends Model
{
    use HasFactory;

    protected $fillable = [
        'queue_id',
        'no_sep',
        'noka',
        'nik',
        'nama_peserta',
        'tgl_lahir_peserta',
        'jenis_kelamin',
        'jenis_peserta',
        'tgl_sep',
        'kode_ppk_pelayanan',
        'ppk_pelayanan',
        'kd_jns_pelayanan',
        'jns_pelayanan',
        'kd_kls_rawat_hak',
        'kls_rawat_hak',
        'kd_kls_rawat_naik',
        'kls_rawat_naik',
        'kd_kls_rawat_pembiayaan',
        'kls_rawat_pembiayaan',
        'kls_rawat_penanggung_jawab',
        'no_mr',
        'kd_asal_rujukan',
        'asal_rujukan',
        'tgl_rujukan',
        'no_rujukan',
        'kd_ppk_rujukan',
        'ppk_rujukan',
        'catatan',
        'kd_diag_awal',
        'diag_awal',
        'kode_poli_tujuan',
        'poli_tujuan',
        'poli_eksekutif',
        'cob',
        'katarak',
        'kd_laka_lantas',
        'laka_lantas',
        'kd_penjamin',
        'penjamin',
        'no_lp',
        'tgl_kejadian_laka',
        'keterangan_laka',
        'suplesi',
        'no_sep_suplesi',
        'kd_provinsi_laka',
        'provinsi_laka',
        'kd_kab_laka',
        'kabupaten_laka',
        'kd_kec_laka',
        'kecamatan_laka',
        'kd_tujuan_kunj',
        'tujuan_kunj',
        'kd_flag_procedur',
        'flag_procedur',
        'kd_penunjang',
        'nama_penunjang',
        'kd_assessment_pel',
        'assessment_pel',
        'no_skdp',
        'kd_skdp_dpjp',
        'skd_dpjp',
        'kd_dpjp_layanan',
        'dpjp_layanan',
        'no_telp',
        'user_create',
        'sumber_sep',
    ];
}